test

diff --git a/.github/workflows/docker-release.yml b/.github/workflows/docker-release.yml
--- a/.github/workflows/docker-release.yml
+++ b/.github/workflows/docker-release.yml
@@ -4,7 +4,7 @@ on:
   push:
     # Publish `master` as Docker `latest` image.
     branches:
-      - main
+      - master
 
     # Publish `v1.2.3` tags as releases.
     tags:
@@ -19,27 +19,7 @@ env:
 jobs:
   # Run tests.
   # See also https://docs.docker.com/docker-hub/builds/automated-testing/
-  build:
-    runs-on: ubuntu-latest
-
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up JDK 11
-        uses: actions/setup-java@v2
-        with:
-          java-version: '11'
-          distribution: 'adopt'
-          cache: maven
-      - name: Build with Maven
-        run: mvn clean verify package -B --update-snapshots -DaltDeploymentRepository=selfcare::https://pkgs.dev.azure.com/pagopaspa/selfcare-projects/_packaging/selfcare/maven/v1
-      - run: mkdir artifact && cp target/*.jar artifact
-      - uses: actions/upload-artifact@v2
-        with:
-          name: Package
-          path: artifact
-
   # test:
-  #   needs: build
   #   runs-on: ubuntu-latest
 
   #   steps:
@@ -53,6 +33,7 @@ jobs:
   #         else
   #           docker build . --file Dockerfile
   #         fi
+
   # Push image to GitHub Package Registry.
   # See also https://docs.docker.com/docker-hub/builds/
   push:
@@ -67,8 +48,13 @@ jobs:
 
       - name: Build image
         run: |
+          echo "current folder: $(pwd)"
+          FROM_SOURCE=$(cat .node-version || cat .nvmrc)
+          ls .node-version && echo ".node-version found, value: '$(cat .node-version)'" || echo ".node-version not found" 
+          ls .nvmrc && echo ".nvmrc found, value: '$(cat .nvmrc)'" || echo ".nvmrc not found"
+          echo "set FROM_SOURCE='$FROM_SOURCE'"
           GITHUB_REPO=$(echo "${{ github.repository }}" | tr '[A-Z]' '[a-z]')
-          docker build . --file Dockerfile --tag $GITHUB_REPO
+          docker build . --file DockerfileRegistry --tag $GITHUB_REPO --build-arg 'NODE_VERSION=$FROM_SOURCE'
 
       - name: Log into registry
         run: |
